export { default as OverviewTab } from './OverviewTab'
export { default as UsersTab } from './UsersTab'
export { default as TeamsTab } from './TeamsTab'
export { default as InstructionsTab } from './InstructionsTab'
export { default as AlertsTab } from './AlertsTab'
export { default as AiLogTab } from './AiLogTab'
export { default as InsightsTab } from './InsightsTab'
export { default as AuditLogTab } from './AuditLogTab'
export { default as ReadConfirmationsTab } from './ReadConfirmationsTab'
export { default as GdprTab } from './GdprTab'

