import { severityColor } from '@/lib/ui-helpers'

/**
 * Shared styles for AdminDashboard components
 * Uses design tokens for consistency
 */
export const createAdminStyles = (isMobile: boolean) => ({
  container: {
    minHeight: '100vh',
    background: '#F8FAFC'
  },
  header: {
    background: '#FFFFFF',
    borderBottom: '1px solid #E2E8F0',
    padding: '12px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky' as const,
    top: 0,
    zIndex: 20,
  },
  logo: {
    fontSize: 20,
    fontWeight: 800,
    background: 'linear-gradient(135deg, #1E3A5F 0%, #2563EB 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  orgName: {
    fontSize: 14,
    color: '#64748B',
    marginLeft: 16,
    fontWeight: 500,
  },
  logoutBtn: {
    padding: '8px 16px',
    fontSize: 14,
    fontWeight: 500,
    background: 'none',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
    color: '#64748B',
    transition: 'all 150ms ease',
  },
  main: {
    display: 'flex',
    flexDirection: isMobile ? ('column' as const) : ('row' as const),
  },
  sidebar: (showMobileMenu: boolean) => ({
    width: isMobile ? '100%' : 240,
    background: '#FFFFFF',
    borderRight: isMobile ? 'none' : '1px solid #E2E8F0',
    borderBottom: isMobile ? '1px solid #E2E8F0' : 'none',
    minHeight: isMobile ? 'auto' : 'calc(100vh - 57px)',
    padding: isMobile ? '8px 12px' : '16px 12px',
    display: isMobile && !showMobileMenu ? 'none' : 'block',
    position: isMobile ? ('relative' as const) : ('sticky' as const),
    top: isMobile ? 'auto' : 57,
    alignSelf: 'flex-start' as const,
  }),
  mobileMenuBtn: {
    display: isMobile ? 'flex' : 'none',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    fontSize: 18,
    background: 'none',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
    color: '#64748B',
  },
  navItem: (active: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '10px 12px',
    fontSize: 14,
    fontWeight: active ? 500 : 400,
    color: active ? '#0F172A' : '#64748B',
    background: active ? '#F1F5F9' : 'transparent',
    border: 'none',
    borderRadius: 8,
    textAlign: 'left' as const,
    cursor: 'pointer',
    transition: 'all 150ms ease',
    marginBottom: 2,
  }),
  navIcon: (active: boolean) => ({
    flexShrink: 0,
    color: active ? '#2563EB' : '#94A3B8',
  }),
  content: {
    flex: 1,
    padding: isMobile ? 16 : 32,
    maxWidth: isMobile ? '100%' : 'calc(100% - 240px)',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 4,
    color: '#0F172A',
    letterSpacing: '-0.02em',
  },
  pageSubtitle: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 24,
    lineHeight: 1.5,
  },
  card: {
    background: '#FFFFFF',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    marginBottom: 16,
    overflow: 'hidden',
  },
  cardHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #E2E8F0',
    fontWeight: 600,
    fontSize: 15,
    color: '#0F172A',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: '#FAFAFA',
  },
  cardBody: {
    padding: 20
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr 1fr' : 'repeat(4, 1fr)',
    gap: 16,
    marginBottom: 28,
  },
  statCard: {
    background: '#FFFFFF',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
    padding: 20,
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    transition: 'box-shadow 200ms ease',
  },
  statIconBox: (color: string) => ({
    width: 40,
    height: 40,
    borderRadius: 10,
    background: color === 'danger' ? '#FEF2F2' : '#F1F5F9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: color === 'danger' ? '#DC2626' : '#2563EB',
    marginBottom: 12,
  }),
  statValue: {
    fontSize: 28,
    fontWeight: 700,
    color: '#0F172A',
    lineHeight: 1.2,
  },
  statLabel: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 4,
    fontWeight: 500,
  },
  btn: {
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 600,
    color: '#FFFFFF',
    background: '#2563EB',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    transition: 'background 150ms ease',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  btnSecondary: {
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 500,
    color: '#334155',
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
    transition: 'all 150ms ease',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  btnDanger: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#DC2626',
    background: '#FEF2F2',
    border: '1px solid #FECACA',
    borderRadius: 6,
    cursor: 'pointer',
    transition: 'all 150ms ease',
  },
  btnSmall: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#64748B',
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 6,
    cursor: 'pointer',
    transition: 'all 150ms ease',
  },
  btnSuccess: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#059669',
    background: '#ECFDF5',
    border: '1px solid #A7F3D0',
    borderRadius: 6,
    cursor: 'pointer',
    transition: 'all 150ms ease',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const
  },
  th: {
    textAlign: 'left' as const,
    padding: '12px 16px',
    fontSize: 12,
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    borderBottom: '1px solid #E2E8F0',
    background: '#FAFAFA',
  },
  td: {
    padding: '14px 16px',
    fontSize: 14,
    borderBottom: '1px solid #F1F5F9',
    color: '#334155',
  },
  badge: (bg: string, color: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 6,
    background: bg,
    color: color,
    gap: 4,
  }),
  modal: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15, 23, 42, 0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
    padding: 16,
  },
  modalContent: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: 28,
    width: '100%',
    maxWidth: 500,
    maxHeight: '90vh',
    overflowY: 'auto' as const,
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 20,
    color: '#0F172A',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
    transition: 'border-color 150ms ease, box-shadow 150ms ease',
    outline: 'none',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
    minHeight: 100,
    resize: 'vertical' as const,
    fontFamily: 'inherit',
    outline: 'none',
    transition: 'border-color 150ms ease, box-shadow 150ms ease',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
    background: '#FFFFFF',
    cursor: 'pointer',
    outline: 'none',
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    marginBottom: 6,
    color: '#334155',
  },
  teamChip: (selected: boolean) => ({
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 999,
    border: selected ? 'none' : '1px solid #E2E8F0',
    background: selected ? '#2563EB' : '#FFFFFF',
    color: selected ? '#FFFFFF' : '#64748B',
    cursor: 'pointer',
    transition: 'all 150ms ease',
  }),
  folderChip: (selected: boolean) => ({
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 8,
    border: selected ? '2px solid #2563EB' : '1px solid #E2E8F0',
    background: selected ? '#EFF6FF' : '#FFFFFF',
    color: selected ? '#2563EB' : '#64748B',
    cursor: 'pointer',
    marginRight: 8,
    marginBottom: 8,
    transition: 'all 150ms ease',
  }),
  alertCard: (severity: string, active: boolean) => ({
    background: active ? severityColor(severity).bg : '#F8FAFC',
    border: `1px solid ${active ? severityColor(severity).color + '40' : '#E2E8F0'}`,
    borderLeft: `4px solid ${active ? severityColor(severity).color : '#E2E8F0'}`,
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    opacity: active ? 1 : 0.7,
    transition: 'all 150ms ease',
  }),
  alertCallout: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: 16,
    borderRadius: 10,
    background: '#FEF2F2',
    borderLeft: '4px solid #DC2626',
    marginBottom: 24,
  },
  filterBar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    padding: 16,
    background: '#FFFFFF',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
  },
  actionBtns: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap' as const,
  },
  logCard: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
  },
  disclaimer: {
    background: '#FFFBEB',
    border: '1px solid #FDE68A',
    borderLeft: '4px solid #F59E0B',
    borderRadius: 10,
    padding: 16,
    marginBottom: 24,
  },
  emptyState: {
    padding: 48,
    textAlign: 'center' as const,
    color: '#64748B',
  },
})
