import { severityColor } from '@/lib/ui-helpers'

/**
 * Shared styles for AdminDashboard components
 * Accepts isMobile boolean to apply responsive styling
 */
export const createAdminStyles = (isMobile: boolean) => ({
  container: { minHeight: '100vh', background: '#F8FAFC' },
  header: {
    background: 'white',
    borderBottom: '1px solid #E2E8F0',
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontSize: 20,
    fontWeight: 800,
    background: 'linear-gradient(135deg, #1E3A5F 0%, #2563EB 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  orgName: { fontSize: 14, color: '#64748B', marginLeft: 16 },
  logoutBtn: {
    padding: '8px 16px',
    fontSize: 14,
    background: 'none',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
  },
  main: {
    display: 'flex',
    flexDirection: isMobile ? ('column' as const) : ('row' as const),
  },
  sidebar: (showMobileMenu: boolean) => ({
    width: isMobile ? '100%' : 220,
    background: 'white',
    borderRight: isMobile ? 'none' : '1px solid #E2E8F0',
    borderBottom: isMobile ? '1px solid #E2E8F0' : 'none',
    minHeight: isMobile ? 'auto' : 'calc(100vh - 65px)',
    padding: isMobile ? '8px 0' : '16px 0',
    display: isMobile && !showMobileMenu ? 'none' : 'block',
  }),
  mobileMenuBtn: {
    display: isMobile ? 'block' : 'none',
    padding: '8px 12px',
    fontSize: 14,
    background: 'none',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
  },
  navItem: (active: boolean) => ({
    display: 'block',
    width: '100%',
    padding: '12px 24px',
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? '#1E3A5F' : '#64748B',
    background: active ? '#EFF6FF' : 'transparent',
    border: 'none',
    textAlign: 'left' as const,
    cursor: 'pointer',
  }),
  content: {
    flex: 1,
    padding: isMobile ? 16 : 24,
  },
  pageTitle: { fontSize: 24, fontWeight: 700, marginBottom: 8 },
  pageSubtitle: { fontSize: 14, color: '#64748B', marginBottom: 24 },
  card: {
    background: 'white',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
    marginBottom: 16,
  },
  cardHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #E2E8F0',
    fontWeight: 600,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardBody: { padding: 20 },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : 'repeat(4, 1fr)',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    background: 'white',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
    padding: 20,
  },
  statValue: { fontSize: 28, fontWeight: 700 },
  statLabel: { fontSize: 13, color: '#64748B', marginTop: 4 },
  btn: {
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 600,
    color: 'white',
    background: '#1E3A5F',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
  btnSecondary: {
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 500,
    color: '#64748B',
    background: 'white',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#DC2626',
    background: '#FEF2F2',
    border: '1px solid #FECACA',
    borderRadius: 6,
    cursor: 'pointer',
  },
  btnSmall: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#64748B',
    background: 'white',
    border: '1px solid #E2E8F0',
    borderRadius: 6,
    cursor: 'pointer',
  },
  btnSuccess: {
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#10B981',
    background: '#ECFDF5',
    border: '1px solid #A7F3D0',
    borderRadius: 6,
    cursor: 'pointer',
  },
  table: { width: '100%', borderCollapse: 'collapse' as const },
  th: {
    textAlign: 'left' as const,
    padding: '12px 16px',
    fontSize: 12,
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    borderBottom: '1px solid #E2E8F0',
  },
  td: {
    padding: '12px 16px',
    fontSize: 14,
    borderBottom: '1px solid #E2E8F0',
  },
  badge: (bg: string, color: string) => ({
    display: 'inline-block',
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 600,
    borderRadius: 999,
    background: bg,
    color: color,
  }),
  modal: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  modalContent: {
    background: 'white',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 500,
    maxHeight: '90vh',
    overflowY: 'auto' as const,
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
    minHeight: 100,
    resize: 'vertical' as const,
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    marginBottom: 16,
    boxSizing: 'border-box' as const,
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    marginBottom: 6,
    color: '#334155',
  },
  teamChip: (selected: boolean) => ({
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 999,
    border: selected ? 'none' : '1px solid #E2E8F0',
    background: selected ? '#1E3A5F' : 'white',
    color: selected ? 'white' : '#64748B',
    cursor: 'pointer',
  }),
  folderChip: (selected: boolean) => ({
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 8,
    border: selected ? '2px solid #1E3A5F' : '1px solid #E2E8F0',
    background: selected ? '#EFF6FF' : 'white',
    color: selected ? '#1E3A5F' : '#64748B',
    cursor: 'pointer',
    marginRight: 8,
    marginBottom: 8,
  }),
  alertCard: (severity: string, active: boolean) => ({
    background: active ? severityColor(severity).bg : '#F8FAFC',
    border: `1px solid ${active ? severityColor(severity).color : '#E2E8F0'}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    opacity: active ? 1 : 0.6,
  }),
  filterBar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    padding: 16,
    background: 'white',
    borderRadius: 12,
    border: '1px solid #E2E8F0',
  },
  actionBtns: { display: 'flex', gap: 8 },
  logCard: {
    background: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  disclaimer: {
    background: '#FEF3C7',
    border: '1px solid #FDE68A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
})
